### ISSUE TITLE
Milestone 3: Add another classifier to modelling

### ISSUE THREAD

**Issue by dbandrews** [UBC-MDS/seismophobia#52]

**Comment by trevorki** [comment]
In trying to add another classifier (logistic regression), I have moved the preprocessor out of the `build_pipeline()` function so it can be used by both classifiers.  Also am thinking of leaving out the feature importance plot since feature importance doesn't exist for logistic regression, and because we will have additional plots coming from the SHAP analysis

**Comment by dbandrews** [comment]
That should work well - there is `coef_` in logistic regression but I'm fine leaving that out

**Comment by dbandrews** [comment]
Closed by #58
